spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=michaelL0@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
jwt.secret=9f2c4b7e8a1d6c3f0e5b9a7d4c2f8e1a6b3d9c7f4a8e2b1c5d7f0a9e3b6c4d8f
jwt.expiration =900000
admin.email=admin@gmail.com
admin.password=12345678